name: Build Win32 DLL

on:
  push:
    branches: [ "main" ]
    paths:
      - 'include/**'
      - 'src/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'include/**'
      - 'src/**'

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:    
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
    - name: Move compiled file
      run: move ${{github.workspace}}\build\Release\serialport.dll ${{github.workspace}}\lib\dls\
      
    - name: Archive artifact
      uses: actions/upload-artifact@v2
      with:
        name: Compiled-Binary
        path: ${{github.workspace}}/lib/dls/
        
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        tag_name: v${{ github.ref }}
        release_name: Release v${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload Asset
      id: upload_asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ github.workspace }}/lib/dls/serialport.dll
        asset_name: serialport.dll
        asset_content_type: application/octet-stream

