name: Build Linux SO

on:
  push:
    branches: [ "main", "github-CI" ]
    paths:
      - 'include/**'
      - 'src/**'
      - '.github/workflows/build_linux.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'include/**'
      - 'src/**'

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:    
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
    - name: Move compiled file
      run: mv ${{github.workspace}}/build/libserialport.so ${{github.workspace}}/lib/dls/
      
    - name: Archive artifact
      uses: actions/upload-artifact@v3
      with:
        name: Compiled-Binary
        path: ${{github.workspace}}/lib/dls/
